name: Build LuCI for naiveproxy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Build Environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential ccache ecj fastjar file g++ gawk \
        gettext git java-propose-classpath libelf-dev libncurses5-dev \
        libncursesw5-dev libssl-dev python python2.7-dev python3 unzip wget \
        python3-distutils python3-setuptools rsync subversion swig time \
        xsltproc zlib1g-dev

    - name: Clone OpenWrt SDK
      run: |
        git clone https://github.com/openwrt/openwrt.git
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Load Custom Feed
      run: |
        cd openwrt
        echo "src-link luci_naiveproxy $GITHUB_WORKSPACE" >> feeds.conf.default
        ./scripts/feeds update luci_naiveproxy
        ./scripts/feeds install -a -p luci_naiveproxy

    - name: Configure OpenWrt
      run: |
        cd openwrt
        cp feeds.conf.default feeds.conf
        echo 'CONFIG_PACKAGE_luci-app-naiveproxy=y' >> .config
        make defconfig

    - name: Build Package
      run: |
        cd openwrt
        make package/luci-app-naiveproxy/compile V=s

    - name: Upload IPK
      uses: actions/upload-artifact@v4
      with:
        name: luci-app-naiveproxy-ipk
        path: openwrt/bin/packages/*/base/luci-app-naiveproxy*.ipk

    - name: Create Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v1
      with:
        files: openwrt/bin/packages/*/base/luci-app-naiveproxy*.ipk
        tag_name: ${{ github.ref_name }}-${{ github.sha }}
        generate_release_notes: true
