name: Build NaiveProxy-Luci IPK
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update

        # Remove lines containing "azure.archive.ubuntu.com" from apt-mirrors.txt
        sudo sed -i '/azure\.archive\.ubuntu\.com/d' /etc/apt/apt-mirrors.txt

        # Print apt-mirrors.txt content to verify removal
        cat /etc/apt/apt-mirrors.txt

        # (Optional) Revert ubuntu.sources back to using mirror+file (if you want to keep using apt-mirrors.txt after cleanup)
        # sudo sed -i 's|^URIs: http://archive.ubuntu.com/ubuntu|URIs: mirror+file:/etc/apt/apt-mirrors.txt|g' /etc/apt/sources.list.d/ubuntu.sources

        # Print ubuntu.sources content
        cat /etc/apt/sources.list.d/ubuntu.sources

        sudo apt-get update
        # Enable multiverse repository (if not already enabled)
        #sudo add-apt-repository multiverse || true
        sudo apt-get update
        sudo apt-get install -y build-essential subversion libncurses5-dev zlib1g-dev gawk gcc texinfo zlib1g-dev lbzip2 git
        sudo apt-get install -y python3 python2-minimal libpython3-dev python3-pip
        pip3 install --upgrade pip
        pip3 install shadowsocks-libev
    # Configure and compile NaiveProxy-Luci
    - name: Build IPK package
      run: |
        # Assuming you have OpenWrt SDK setup in 'openwrt' directory
        cd openwrt
        # Update feeds
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        # Copy the custom package (NaiveProxy-Luci) into package directory
        cp -r ../../packages/luci-app-naiveproxy ./package/feeds/custom/luci-app-naiveproxy
        # Update and build
        make defconfig
        make -j4 download
        make -j4 V=s
        # Package the IPK
        make package/index
        # Collect the generated IPK
        cp bin/packages/flower/luci-app-naiveproxy_*.ipk ../release/
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: naiveproxy-luci.ipk
        path: release/luci-app-naiveproxy_*.ipk
