name: Build LuCI for naiveproxy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
          
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup Build Environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential ccache ecj fastjar file g++ gawk \
        gettext git java-propose-classpath libelf-dev libncurses5-dev \
        libncursesw5-dev libssl-dev python python2.7-dev python3 unzip wget \
        python3-distutils python3-setuptools rsync subversion swig time \
        xsltproc zlib1g-dev

    - name: Download OpenWrt SDK
      run: |
        wget https://downloads.openwrt.org/releases/22.03.5/targets/x86/64/openwrt-sdk-22.03.5-x86-64_gcc-11.2.0_musl.Linux-x86_64.tar.xz
        tar xf openwrt-sdk-22.03.5-x86-64_gcc-11.2.0_musl.Linux-x86_64.tar.xz
        mv openwrt-sdk-22.03.5-x86-64_gcc-11.2.0_musl.Linux-x86_64 sdk

    - name: Update Feed
      run: |
        cd sdk
        echo "src-link luci_naiveproxy $GITHUB_WORKSPACE" >> feeds.conf.default
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Configure SDK
      run: |
        cd sdk
        cat > .config <<EOF
        CONFIG_ALL_NONSHARED=n
        CONFIG_ALL_KMODS=n
        CONFIG_ALL=n
        CONFIG_PACKAGE_luci-app-naiveproxy=y
        CONFIG_PACKAGE_naiveproxy=y
        EOF
        make defconfig

    - name: Build Package
      run: |
        cd sdk
        make package/luci-app-naiveproxy/compile V=sc

    - name: Show Build Results
      if: always()
      run: |
        cd sdk
        echo "============== Build Directory =============="
        ls -R bin/packages/
        echo "============== Package Contents =============="
        find bin/packages/ -name "*.ipk" -exec ls -l {} \;
        # 只在logs目录存在时才查找日志
        if [ -d logs ]; then
          echo "============== Log Files =============="
          find logs/ -type f -name "*.txt" -exec cat {} \;
        fi

    - name: Upload Packages
      uses: actions/upload-artifact@v4
      with:
        name: luci-packages-${{ matrix.arch }}
        path: |
          sdk/bin/packages/**/*.ipk

          
    - name: Create Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v1
      with:
        files: sdk/bin/packages/**/*.ipk
        tag_name: v${{ github.run_number }}
        title: Release ${{ github.run_number }}
        generate_release_notes: true

