name: Debug Feeds and diffconfig

on:
  workflow_dispatch: # 仅手动触发

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential g++ binutils bzip2 flex python3 perl make wget curl git rsync unzip libncurses5-dev zlib1g-dev gawk gettext libssl-dev python3-setuptools python-is-python3

      - name: Clone OpenWrt source code
        run: |
          rm -rf openwrt-source
          git clone https://git.openwrt.org/openwrt/openwrt.git openwrt-source
          cd openwrt-source

      - name: Clean feeds and packages directories
        run: |
          cd openwrt-source
          rm -rf feeds/* packages/*

      - name: Update and install feeds (verbose output, corrected option)
        run: |
          cd openwrt-source
          ./scripts/feeds update -a --verbose
          ./scripts/feeds install -a --verbose

      - name: Check for diffconfig after feeds install
        run: |
          cd openwrt-source
          ls -l scripts/diffconfig
          if [ ! -f scripts/diffconfig ]; then
            echo "Error: scripts/diffconfig is still missing after feeds install!"
            exit 1
          fi
